ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS sellos INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS sellos_canjeados INTEGER NOT NULL DEFAULT 0;

ALTER TABLE pagos ADD COLUMN IF NOT EXISTS visita_gratis BOOLEAN NOT NULL DEFAULT FALSE;
